### ISSUE TITLE
Pressing backspace doesn't delete and instead takes user back to the previous page

### ISSUE THREAD

**Issue by maxwang7** [precup/turing-machine-sim#118] opened 2015-05-06 08:22 UTC
Brendon did this twice and lost his data, and could be a major point of frustration for students. At the very least, I think we should have a popup from the browser that asks the user to confirm that he/she wants to leave the page without saving.

**Comment by precup** [comment] 2015-05-08 06:23
Easily fixed, just say we don't support Macs

**Comment by precup** [comment] 2015-05-08 07:32
Should this delete the nodes, do nothing, or warn the user before going back?

**Comment by moonj** [comment] 2015-05-09 05:44
This is two problems in one:

We should have a confirm popup before leaving the page in any way (closing, going back, maybe even refreshing?) that lets users immediately access the save popup as well.

And backspacing should delete the nodes. That feels natural to me and I suspect that feels natural for a lot of people.

**Comment by moonj** [comment] 2015-05-09 05:45
That popup window should probably be a js alert

**Comment by precup** [comment] 2015-05-15 04:35
I just fixed the backspace issue, I'm closing this as it is now a duplicate of (@26)[https://github.com/precup/turing-machine-sim/issues/26]

**Closed by precup** 2015-05-15 04:35 UTC
Labels: All
